export const slideTemplates = {
    fullImage: {
        type: 'fullImage',
        name: 'Full Image',
        visible: true,
        size: 'regular',
        mobileSize: 'regular',
        src: '',
        alt: '',
        backgroundColor: '#ffffff',
        useZoom: false,
        imagePosition: 'center center',
        imageScale: 1,
        imageTransform: {
            scale: 100,        // percentage (100 = original size)
            translateX: 0,     // pixels
            translateY: 0,     // pixels
            rotate: 0          // degrees
        },
        link: '',
        button: null
    },
    fullImageWithText: {
        type: 'fullImageWithText',
        name: 'Image with Text',
        visible: true,
        size: 'regular',
        mobileSize: 'regular',
        src: '',
        alt: '',
        backgroundColor: '#ffffff',
        title: 'Your Title Here',
        text: 'Your text content here',
        textPosition: 'bottom',
        textWidth: '100%',
        titleColor: '#ffffff',
        textColor: '#ffffff',
        titleFontSize: 24,
        titleFontSizeMobile: 16,
        textFontSize: 14,
        textFontSizeMobile: 12,
        useFillOverlay: false,
        fillColor: '#000000',
        fillHeight: '50%',
        fillDirection: 'bottom',
        useGradient: true,
        gradientColor: '#000000',
        gradientHeight: '50%',
        gradientDirection: 'bottom',
        useZoom: false,
        imagePosition: 'center center',
        imageScale: 1,
        imageTransform: {
            scale: 100,        // percentage (100 = original size)
            translateX: 0,     // pixels
            translateY: 0,     // pixels
            rotate: 0          // degrees
        },
        link: '',
        button: null
    },
    text: {
        type: 'text',
        name: 'Text Only',
        visible: true,
        size: 'regular',
        mobileSize: 'regular',
        title: 'Your Title Here',
        text: 'Your text content here',
        backgroundColor: '#ffffff',
        titleColor: '#13264A',
        textColor: '#333333',
        titleFontSize: 22,
        titleFontSizeMobile: 18,
        textFontSize: 16,
        textFontSizeMobile: 14,
        link: '',
        button: null
    },
    video: {
        type: 'video',
        name: 'Video',
        visible: true,
        size: 'regular',
        mobileSize: 'regular',
        src: '',
        posterSrc: '',
        alt: 'Video',
        videoPosition: 'center center',
        videoScale: 1,
        link: '',
        button: null
    },
    fullVideoWithText: {
        type: 'fullVideoWithText',
        name: 'Video with Text',
        visible: true,
        size: 'regular',
        mobileSize: 'regular',
        src: '',
        posterSrc: '',
        alt: 'Video',
        title: 'Your Title Here',
        text: 'Your text content here',
        textPosition: 'bottom',
        textWidth: '100%',
        textColor: '#ffffff',
        titleFontSize: 24,
        titleFontSizeMobile: 16,
        textFontSize: 14,
        textFontSizeMobile: 12,
        useFillOverlay: false,
        fillColor: '#000000',
        fillHeight: '50%',
        fillDirection: 'bottom',
        useGradient: true,
        gradientColor: '#000000',
        gradientHeight: '50%',
        gradientDirection: 'bottom',
        videoPosition: 'center center',
        videoScale: 1,
        link: '',
        button: null
    },
    bigNumber: {
        type: 'bigNumber',
        name: 'Big Numbers',
        visible: true,
        size: 'regular',
        mobileSize: 'regular',
        numberOne: '85%',
        textOne: 'First statistic description',
        numberTwo: '42',
        textTwo: 'Second statistic description',
        backgroundColor: '#ffffff',
        numberColor: '#13264A',
        textColor: '#333333',
        numberFontSize: 40,
        numberFontSizeMobile: 32,
        textFontSize: 16,
        textFontSizeMobile: 14,
        link: '',
        button: null
    },
    imageSelector: {
        type: 'imageSelector',
        name: 'Image Selector',
        visible: true,
        size: 'regular',
        mobileSize: 'regular',
        backgroundColor: '#EFF2F7',
        imageWidth: '60%',
        textColor: '#333333',
        dotColor: '#cccccc',
        dotActiveColor: '#13264A',
        link: '',
        images: []
    }
};
