export const slideTemplates = {
    fullImage: {
        type: 'fullImage',
        name: 'Full Image',
        size: 'regular',
        src: '',
        alt: '',
        useZoom: false,
        imagePosition: 'center center',
        imageScale: 1,
        link: '',
        button: null
    },
    fullImageWithText: {
        type: 'fullImageWithText',
        name: 'Image with Text',
        size: 'regular',
        src: '',
        alt: '',
        title: 'Your Title Here',
        text: 'Your text content here',
        textPosition: 'bottom',
        textWidth: '100%',
        textColor: '#ffffff',
        titleFontSize: 24,
        textFontSize: 14,
        useGradient: true,
        gradientColor: '#000000',
        gradientHeight: '50%',
        useZoom: false,
        imagePosition: 'center center',
        imageScale: 1,
        link: '',
        button: null
    },
    text: {
        type: 'text',
        name: 'Text Only',
        size: 'regular',
        title: 'Your Title Here',
        text: 'Your text content here',
        backgroundColor: '#ffffff',
        titleColor: '#13264A',
        textColor: '#333333',
        titleFontSize: 22,
        textFontSize: 16,
        button: null
    },
    video: {
        type: 'video',
        name: 'Video',
        size: 'regular',
        src: '',
        posterSrc: '',
        alt: 'Video',
        videoPosition: 'center center',
        videoScale: 1,
        button: null
    },
    fullVideoWithText: {
        type: 'fullVideoWithText',
        name: 'Video with Text',
        size: 'regular',
        src: '',
        posterSrc: '',
        alt: 'Video',
        title: 'Your Title Here',
        text: 'Your text content here',
        textPosition: 'bottom',
        textWidth: '100%',
        textColor: '#ffffff',
        titleFontSize: 24,
        textFontSize: 14,
        useGradient: true,
        gradientColor: '#000000',
        gradientHeight: '50%',
        videoPosition: 'center center',
        videoScale: 1,
        button: null
    },
    bigNumber: {
        type: 'bigNumber',
        name: 'Big Numbers',
        size: 'regular',
        numberOne: '85%',
        textOne: 'First statistic description',
        numberTwo: '42',
        textTwo: 'Second statistic description',
        backgroundColor: '#ffffff',
        numberColor: '#13264A',
        textColor: '#333333',
        numberFontSize: 40,
        textFontSize: 16,
        button: null
    },
    imageSelector: {
        type: 'imageSelector',
        name: 'Image Selector',
        size: 'regular',
        backgroundColor: '#EFF2F7',
        imageWidth: '60%',
        textColor: '#333333',
        dotColor: '#cccccc',
        dotActiveColor: '#13264A',
        images: []
    }
};
